### ISSUE TITLE
Komodo Notary Season 4

### ISSUE THREAD

**Issue by tonymorony** [emc2foundation/einsteinium#16]
Dear Einsteinium team ,

We are pleased to release the new Komodo 0.6.0 version, called "Draconic Serpent," which will hardfork the Komodo network to the 4th dPoW season on June 14th, 2020.
Exact height/timestamp can be found here ( approx. June 14th, 2020 03:00:00 PM UTC) : https://github.com/KomodoPlatform/komodo/blob/master/src/komodo_globals.h#L48

List of the third-party pubkeys for this season can be found here: https://github.com/KomodoPlatform/dPoW/blob/s4/iguana/3rd_party#L15

Please update your codebase accordingly for dPoW consensus protection and update infrastructure daemons/exchanges. We recommend contacting exchanges you listed on to pause all wallet-operations (withdraws & deposits) from June 13th, 12:00 PM UTC until June 15th 12:00 PM UTC in order to ensure a smooth network transition.

In case of questions don't hesitate to contact me by email `alysakov at komodoplatform.com` or in TG `@ jl777fan`

Have a great day and stay safe!

**Comment by emc2foundation** [comment]
Thank you for the update @tonymorony !
We are preparing necessary changes and planning to update our nodes in upcoming days.
Best Regards,
Einsteinium team
