### ISSUE TITLE
Updates required for KMD Season 5 Hardfork

### ISSUE THREAD

**Issue by smk762** [emc2foundation/einsteinium#21]
https://github.com/emc2foundation/einsteinium/blob/master/src/komodo_notaries.h needs update, refer to https://github.com/KomodoPlatform/komodo/blob/master/src/komodo_defs.h & https://github.com/KomodoPlatform/komodo/blob/master/src/komodo_globals.h
for season hardfork time etc.

new pubkeys in here - https://github.com/emc2foundation/einsteinium/pull/20

@emc2foundation contact Komodo Support via discord or keybase if you need help.

**Comment by emc2foundation** [comment]
Hi @smk762 thanks for opening the issue!
What is the estimate date for Season 5 Hardfork? Seeing in the EMC2 PR [#20](https://github.com/emc2foundation/einsteinium/pull/20) that its set to ~July 4th and in KMD code and blog post its set for June 14th, 2021.

**Comment by emc2foundation** [comment]
Hi @smk762 we pushed the needed code into the **master** branch. Details could be found here:
https://www.emc2.foundation/emc2-blog/2021/6/11/emc2-wallet-upgrade-notice
Please propagate this message to the KMD notary nodes for upgrade.

**Comment by smk762** [comment]
Thanks!
Linked PR for update - https://github.com/KomodoPlatform/dPoW/pull/332
