### ISSUE TITLE
Block source unavaliable one week already

### ISSUE THREAD

**Issue by jedihem** [emc2foundation/einsteinium#24]
Hello! How can i fix this? Last Windows wallet and last Linux wallet same problem. Thanks

**Comment by SickProdigy** [comment]
You should be able to grab nodes from this source
https://chainz.cryptoid.info/emc2/api.dws?q=nodes

and then add them from within emc2 core console within debug menu
using
addnode IP add

Not quite working for me but maybe for you.

**Comment by emc2foundation** [comment]
Hi @jedihem @SickProdigy ,

Thank you for reporting the issue..
Recently we had disturbance in DNS Seeder service, its up and running again so wallets should connect automatically on startup. There is no need to add nodes manually anymore, but if you still experiencing issues let us know.

**Comment by jedihem** [comment]
> You should be able to grab nodes from this source

Many thnx! it works
But very slowly - 100,000 blocks  in 12 hours. I would like the network to be faster. Not good for a node on a pool
