### ISSUE TITLE
Travis Build Error

### ISSUE THREAD

**Issue by mx1010** [emc2foundation/einsteinium#4]
Looking to invest but I'm trying to get a good overview of the tech behind your project. I see that the  build failed 3 months ago and hasn't been addressed. 

Just curious if there are any plans to pick this back up.

https://travis-ci.org/emc2foundation/einsteinium

**Comment by hackmod** [comment]
no response == no dev...

**Comment by mx1010** [comment]
Seems to be the case here ¯\_(ツ)_/¯
