### ISSUE TITLE
New Einsteinium wallet does not run on macOS 10.12

### ISSUE THREAD

**Issue by sunk818** [emc2foundation/einsteinium#5]
Is there a way I can build a wallet that is compatible with 10.12? Says I need 10.13 and I don't want to upgrade my macOS version. Another program I use requires 10.12 (usb to serial driver).

**Comment by emc2foundation** [comment]
You can find build for macOS compatible with version 10.12 on wallets download page on the official website: https://www.emc2.foundation/wallets
